In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import BaggingClassifier
from sqlalchemy import create_engine
from sklearn.datasets import make_classification

In [2]:
engine = create_engine("mysql+pymysql://root:@localhost/psd")
query = "SELECT mcg, gvh, lip, chg, aac, alm1, alm2, localization_class FROM ecoli"
df = pd.read_sql(query, engine)

X = df.drop(columns=["localization_class"])
y = df["localization_class"]

df

      mcg   gvh   lip  chg   aac  alm1  alm2 localization_class
0    0.49  0.29  0.48  0.5  0.56  0.24  0.35                 cp
1    0.07  0.40  0.48  0.5  0.54  0.35  0.44                 cp
2    0.56  0.40  0.48  0.5  0.49  0.37  0.46                 cp
3    0.59  0.49  0.48  0.5  0.52  0.45  0.36                 cp
4    0.23  0.32  0.48  0.5  0.55  0.25  0.35                 cp
..    ...   ...   ...  ...   ...   ...   ...                ...
331  0.74  0.56  0.48  0.5  0.47  0.68  0.30                 pp
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32                 pp
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38                 pp
334  0.59  0.61  0.48  0.5  0.42  0.42  0.37                 pp
335  0.74  0.74  0.48  0.5  0.31  0.53  0.52                 pp

[336 rows x 8 columns]

In [3]:
data_smote = pd.read_csv("../oversampling/hasil_oversampling_SMOTE.csv")
x_smote = data_smote.drop(columns=["class"])
y_smote = data_smote["class"]
data_smote

           mcg       gvh   lip  chg       aac      alm1      alm2 class
0     0.490000  0.290000  0.48  0.5  0.560000  0.240000  0.350000    cp
1     0.070000  0.400000  0.48  0.5  0.540000  0.350000  0.440000    cp
2     0.560000  0.400000  0.48  0.5  0.490000  0.370000  0.460000    cp
3     0.590000  0.490000  0.48  0.5  0.520000  0.450000  0.360000    cp
4     0.230000  0.320000  0.48  0.5  0.550000  0.250000  0.350000    cp
...        ...       ...   ...  ...       ...       ...       ...   ...
1149  0.469299  0.408934  0.48  0.5  0.554117  0.624964  0.624336    im
1150  0.363254  0.549534  0.48  0.5  0.443720  0.708834  0.549528    im
1151  0.502068  0.467368  0.48  0.5  0.150052  0.794735  0.448992    im
1152  0.577332  0.649453  0.48  0.5  0.630424  0.744364  0.722243    im
1153  0.510713  0.490693  0.48  0.5  0.493466  0.859327  0.872772    im

[1154 rows x 8 columns]

In [4]:
data_adasyn = pd.read_csv("../oversampling/hasil_oversampling_ADASYn.csv")
x_adasyn = data_adasyn.drop(columns=["class"])
y_adasyn = data_adasyn["class"]
data_adasyn

           mcg       gvh   lip  chg       aac      alm1      alm2 class
0     0.490000  0.290000  0.48  0.5  0.560000  0.240000  0.350000    cp
1     0.070000  0.400000  0.48  0.5  0.540000  0.350000  0.440000    cp
2     0.560000  0.400000  0.48  0.5  0.490000  0.370000  0.460000    cp
3     0.590000  0.490000  0.48  0.5  0.520000  0.450000  0.360000    cp
4     0.230000  0.320000  0.48  0.5  0.550000  0.250000  0.350000    cp
...        ...       ...   ...  ...       ...       ...       ...   ...
1149  0.469299  0.408934  0.48  0.5  0.554117  0.624964  0.624336    im
1150  0.363254  0.549534  0.48  0.5  0.443720  0.708834  0.549528    im
1151  0.502068  0.467368  0.48  0.5  0.150052  0.794735  0.448992    im
1152  0.577332  0.649453  0.48  0.5  0.630424  0.744364  0.722243    im
1153  0.510713  0.490693  0.48  0.5  0.493466  0.859327  0.872772    im

[1154 rows x 8 columns]

# BaggingClassifier Menggunakan Metode Naive Bayes

## BaggingClassifier pada data yang belum di lakukan oversampling

In [5]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)

clf = BaggingClassifier(estimator=GaussianNB(),
                        n_estimators=100, random_state=0).fit(X, y)


prediksi = clf.predict(X_test)

print(f"accuracy_score : {accuracy_score(y_test, prediksi)}")
print("Classification Report:\n", classification_report(y_test, prediksi))

C:\Users\USERB-PC\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but BaggingClassifier was fitted without feature names
  warnings.warn(

ValueError: X has 7 features, but BaggingClassifier is expecting 4 features as input.

## BaggingClassifier pada data yang sudah di lakukan oversampling dengan SMOTE

In [24]:

X_train, X_test, y_train, y_test = train_test_split(
    x_smote, y_smote, test_size=0.2, random_state=42
)

X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)

clf = BaggingClassifier(estimator=GaussianNB(),
                        n_estimators=100, random_state=0).fit(x_smote, y_smote)


prediksi = clf.predict(X_test)

print(f"accuracy_score : {accuracy_score(y_test, prediksi)}")
print("Classification Report:\n", classification_report(y_test, prediksi))

accuracy_score : 0.8398268398268398
Classification Report:
               precision    recall  f1-score   support

          cp       0.86      0.97      0.91        32
          im       0.87      0.48      0.62        27
         imL       1.00      1.00      1.00        30
         imS       1.00      1.00      1.00        29
         imU       0.74      0.82      0.78        28
          om       1.00      0.37      0.54        27
         omL       1.00      1.00      1.00        27
          pp       0.58      1.00      0.74        31

    accuracy                           0.84       231
   macro avg       0.88      0.83      0.82       231
weighted avg       0.88      0.84      0.83       231

## BaggingClassifier pada data yang sudah di lakukan oversampling dengan ADASYN

In [31]:

X_train, X_test, y_train, y_test = train_test_split(
    x_adasyn, y_adasyn, test_size=0.2, random_state=42
)

X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)

clf = BaggingClassifier(estimator=GaussianNB(),
                        n_estimators=100, random_state=0).fit(x_adasyn, y_adasyn)


prediksi = clf.predict(X_test)

print(f"accuracy_score : {accuracy_score(y_test, prediksi)}")
print("Classification Report:\n", classification_report(y_test, prediksi))

accuracy_score : 0.8744588744588745
Classification Report:
               precision    recall  f1-score   support

          cp       0.91      0.97      0.94        32
          im       0.89      0.59      0.71        27
         imL       1.00      1.00      1.00        30
         imS       0.91      1.00      0.95        29
         imU       0.81      0.79      0.80        28
          om       1.00      0.59      0.74        27
         omL       1.00      1.00      1.00        27
          pp       0.66      1.00      0.79        31

    accuracy                           0.87       231
   macro avg       0.90      0.87      0.87       231
weighted avg       0.89      0.87      0.87       231